version: '3'
networks:
    mapswipe_network:
        driver: bridge
        ipam:
            config: [{subnet: 172.20.0.0/16}]
    api:
    manager_dashboard:
    mapswipe_workers:
    postgres:

services:
    nginx:
        container_name: nginx
        build:
            context: nginx/
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        networks:
            - mapswipe_network
            - api
            - manager_dashboard

    api:
        container_name: api
        build:
            context: api/
        volumes:
            - ./mapswipe-data/api:/usr/share/nginx/html/api/:ro
        restart: unless-stopped
        expose:
            - "80"
        networks:
            - api

    manager_dashboard:
        container_name: manager_dashboard
        build:
            context: manager_dashboard/
        restart: unless-stopped
        expose:
            - "80"
        networks:
            - manager_dashboard

    mapswipe_workers:
        container_name: mapswipe_workers
        build:
            context: mapswipe_workers/
        environment:
            FIREBASE_DB: '${FIREBASE_DB}'
            FIREBASE_API_KEY: '${FIREBASE_API_KEY}'
            FIREBASE_TOKEN: '${FIREBASE_TOKEN}'
            GOOGLE_APPLICATION_CREDENTIALS: 'serviceAccountKey.json'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
            POSTGRES_HOST: 'postgres'
            POSTGRES_PORT: 5432
            PGDATA: '/var/lib/postgresql/mapswipe'
            IMAGE_BING_API_KEY: '${IMAGE_BING_API_KEY}'
            IMAGE_ESRI_API_KEY: '${IMAGE_ESRI_API_KEY}'
            IMAGE_ESRI_BETA_API_KEY: '${IMAGE_ESRI_BETA_API_KEY}'
            IMAGE_MAPBOX_API_KEY: '${IMAGE_MAPBOX_API_KEY}'
            IMAGE_MAXAR_PREMIUM_API_KEY: '${IMAGE_MAXAR_PREMIUM_API_KEY}'
            IMAGE_MAXAR_STANDARD_API_KEY: '${IMAGE_MAXAR_STANDARD_API_KEY}'
            SLACK_TOKEN: '${SLACK_TOKEN}'
            SLACK_CHANNEL: '${SLACK_CHANNEL}'
            SENTRY_DSN: '${SENTRY_DSN}'
        depends_on:
            - postgres
        command: mapswipe_workers --verbose run --schedule
        volumes:
            - ./mapswipe-data:/root/.local/share/mapswipe_workers
        restart: "no"
        networks:
            - mapswipe_workers
            - postgres

    postgres:
        container_name: postgres
        build:
            context: postgres/
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
            PGDATA: '/var/lib/postgresql/mapswipe'
            WALG_GS_PREFIX: '${WALG_GS_PREFIX}'
            GOOGLE_APPLICATION_CREDENTIALS: '/serviceAccountKey.json'
        # Set options for WAL-G (backup tool)
        command: postgres -c archive_mode=on -c archive_timeout=60 -c archive_command="/archive_command.sh %p"
        volumes:
          - ./postgres-data:/var/lib/postgresql/mapswipe
        restart: unless-stopped
        ports:
          - "5432:5432"
        networks:
            - postgres

    postgres_recovery:
        container_name: postgres_recovery
        build:
            context: postgres/recovery/
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
            PGDATA: '/var/lib/postgresql/mapswipe'
            WALG_GS_PREFIX: '${WALG_GS_PREFIX}'
            GOOGLE_APPLICATION_CREDENTIALS: '/serviceAccountKey.json'
        volumes:
            - ./pgdata_restored:/var/lib/postgresql/mapswipe
        ports:
          - "5445:5432"

    firebase_deploy:
        container_name: firebase_deploy
        build:
            context: firebase/
        environment:
            FIREBASE_TOKEN: '${FIREBASE_TOKEN}'
            FIREBASE_DB: '${FIREBASE_DB}'
        command: sh -c "firebase use $FIREBASE_DB && firebase deploy --token $FIREBASE_TOKEN --only functions,database:rules"
        volumes:
            - ./firebase:/firebase
