version: "3"
services:
  oqt-website:
    ports:
      - "80:80"

  oqt-workers:
    container_name: oqt-workers
    build:
      context: workers/
      dockerfile: Dockerfile
    environment:
      OQT_OHSOME_API: '${OHSOME_API}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PORT: '${POSTGRES_PORT}'
      POSTGRES_HOST: '${POSTGRES_HOST}'
      POSTGRES_SCHEMA: '${POSTGRES_SCHEMA}'
    command: uvicorn ohsome_quality_analyst.api:app --host 0.0.0.0 --port 8000 --reload
    restart: "unless-stopped"
    ports:
      - "8080:8000"
    networks:
      - oqt-network

  oqt-website:
    container_name: oqt-website
    build:
      context: website/
      dockerfile: Dockerfile
    restart: "unless-stopped"
    ports:
      - "80:80"
    networks:
      - oqt-network

networks:
  oqt-network:
