__version__ = "0.8.0"
__title__ = "ohsome quality analyst"
__description__ = "Intrinsic and extrinsic data quality metrics for OpenStreetMap data."
__author__ = "ohsome team"
__email__ = "ohsome@heigit.org"
__homepage__ = "https://oqt.ohsome.org/"
