---
# Database connection parameters (required)
postgres_host: localhost
postgres_port: 5445
postgres_db: oqapi
postgres_user: oqapi
postgres_password: oqapi

# ohsome API configuration
ohsome_api_url: https://ohsome-api.heigitk8s.de
heigit_api_key:

# Defaults to 'ohsome-quality-api/{version}'
user_agent:

# FastAPI configuration
root_path: /ohsome-quality-api/v2
docs_url: /docs

# Python logging level
log_level: INFO

# Limit number of concurrent Indicator computations
concurrent_computations: 4
