---
# Database connection parameters;
ohsomedb_host: localhost
ohsomedb_port: 5432
ohsomedb_db: postgres
ohsomedb_user: postgres
ohsomedb_password: mylocalpassword
postgres_host: localhost
postgres_port: 5445
postgres_db: oqapi
postgres_user: oqapi
postgres_password: oqapi
# Restrict size of input geometry
geom_size_limit: 1000
# Python logging level
log_level: INFO
# ohsome API URL
ohsome_api: https://api.ohsome.org/v1
# Limit number of concurrent Indicator computations
concurrent_computations: 4
# User-Agent header for request to the ohsome API
# Default: 'ohsome-quality-api/{version}'
user_agent: ohsome-quality-api
