__version__ = "1.11.2"
__title__ = "ohsome quality API"
__description__ = "Data quality estimations for OpenStreetMap"
__author__ = "ohsome team"
__email__ = "ohsome@heigit.org"
__homepage__ = "https://api.quality.ohsome.org/"
