# ohsomehex-db Postgis version is 10
FROM postgis/postgis:10-3.0

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    gzip

RUN mkdir -p /data
RUN chmod -R 777 /data

COPY ./data/ /data/

RUN pg_restore --version

# Initialization scripts.
# https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts
COPY init-db.sql /docker-entrypoint-initdb.d/1-init-db.sql
COPY admin-schema.sql /docker-entrypoint-initdb.d/2-admin-schema.sql
COPY restore-dev-tables.sh docker-entrypoint-initdb.d/3-restore-dev-tables.sh
COPY create-indices.sql docker-entrypoint-initdb.d/4-create-indices.sql
COPY zonal-stats.sql docker-entrypoint-initdb.d/4-zonal-stats.sql
