---
version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(filename)s - %(funcName)s - %(message)s"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
root:
  handlers: [default]
  level: INFO
