FROM oqt-workers:latest

USER root:root

# install java and node for sonar-scanner
RUN apt-get update && \
    apt-get install --yes --no-install-recommends openjdk-17-jre-headless nodejs && \
    rm -rf /var/lib/apt/lists/*

USER oqt:oqt
